teleop:
  move:
    type: topic
    message_type: geometry_msgs/Twist
    topic_name: cmd_vel
    deadman_buttons: [ ]
    axis_mappings:
      - axis: 0
        target: linear.y
        scale: 1.0
      - axis: 1
        target: linear.x
        scale: 1.0
      - axis: 3
        target: angular.z
        scale: 1.0

  mode:
    type: topic
    message_type: legged_controllers/gait_command
    topic_name: joy_command
    deadman_buttons: [ ]
    axis_mappings:
      # gait switch
      - button: 0
        target: A
        scale: 1.0
      - button: 1
        target: B
        scale: 1.0
      - button: 2
        target: X
        scale: 1.0
      - button: 3
        target: Y
        scale: 1.0
      # locomotion switch
      - button: 5
        target: RB
        scale: 1.0
      # position control
      - button: 4
        target: LB
        scale: 1.0
      - axis: 2
        target: LT
        scale: 1.0
